export default [
  {
    id: 1,
    ingredientName: "huju",
    ingredientCost: 30,
    ingredientWeight: 4800,
    ingredientRatio: 1.6,
  },
  {
    id: 2,
    ingredientName: "sol",
    ingredientCost: 10,
    ingredientWeight: 8090,
    ingredientRatio: 1.2,
  },
  {
    id: 3,
    ingredientName: "kolor",
    ingredientCost: 20,
    ingredientWeight: 10700,
    ingredientRatio: 1.1,
  },
  {
    id: 99,
    ingredientName: "judfasd",
    ingredientCost: 10,
    ingredientWeight: 8090,
    ingredientRatio: 1.2,
  },
  {
    id: 4,
    ingredientName: "olej 5l",
    ingredientCost: 3,
    ingredientWeight: 3454,
    ingredientRatio: 1.5,
  },
  {
    id: 5,
    ingredientName: "witamina asd",
    ingredientCost: 14,
    ingredientWeight: 13000,
    ingredientRatio: 1.9,
  },
  {
    id: 6,
    ingredientName: "swiezb ci do tego",
    ingredientCost: 6,
    ingredientWeight: 10,
    ingredientRatio: 5.2,
  },
];
