export default [
  {
    id: 5,
    productName: "mydlo kokosowe",
    componentList: [
      {
        componentCost: 4969.5,
        componentWeight: 4545,
        id: 905617,
        ingredientName: "kolor",
        ingredientRatio: 1.1,
        productRatio: 4545,
        usedCost: 0,
        usedWeight: 0,
      },
      {
        componentCost: 176.8,
        componentWeight: 34,
        id: 252514,
        ingredientName: "swiezb",
        ingredientRatio: 5.2,
        productRatio: 20,
        usedCost: 0,
        usedWeight: 0,
      },
      {
        componentCost: 54,
        componentWeight: 34,
        id: 441149,
        ingredientName: "olej",
        ingredientRatio: 1.5,
        productRatio: 56,
        usedCost: 0,
        usedWeight: 0,
      },
      {
        componentCost: 4969.5,
        componentWeight: 4545,
        id: 905517,
        ingredientName: "dsaa",
        ingredientRatio: 1.1,
        productRatio: 100,
        usedCost: 0,
        usedWeight: 0,
      },
    ],
  },
];
