export const INGREDIENT_ADD = "INGREDIENT_ADD";
export const INGREDIENT_DELETE = "INGREDIENT_DELETE";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const INGREDIENT_EDIT = "INGREDIENT_EDIT";
